package live

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/dongfang/dfchat/server/internal/moderation"
)

// RunModerationLoop polls every IntervalSeconds for currently
// broadcasting rooms, asks the configured AI providers to look at
// each room's latest thumbnail, and files a system report
// (reporter_id = NULL) when any category exceeds the threshold.
//
// Same admin queue + UI as user reports — admin sees AI flags and
// human flags side by side, with AI's stated reason in the note
// field. Evidence images are captured AT FLAG TIME and copied to a
// permanent /opt/dfchat-live/data/evidence/<report_id>.jpg path so
// later review survives the 30 s thumbnail churn (this path doesn't
// exist yet — see evidence_archive.go for the helper).
//
// Stateless per-tick. If the api restarts mid-tick the worst case
// is one duplicate flag (the partial unique index catches dupes
// from the same provider for the same reason within a status=0
// window).
func (h *Handler) RunModerationLoop(ctx context.Context, cfg moderation.Config, log *slog.Logger) {
	if !cfg.Enabled {
		log.Info("moderation worker: disabled (MODERATION_ENABLED=false)")
		return
	}
	providers, err := moderation.Build(cfg)
	if err != nil {
		log.Warn("moderation worker: not starting", "err", err.Error())
		return
	}
	names := make([]string, 0, len(providers))
	for _, p := range providers {
		names = append(names, p.Name())
	}
	log.Info("moderation worker: started",
		"providers", names,
		"intervalSeconds", cfg.IntervalSeconds,
		"threshold", cfg.Threshold)

	tick := time.Duration(cfg.IntervalSeconds) * time.Second
	if tick < 10*time.Second {
		tick = 60 * time.Second
	}
	// CRITICAL: the ticker + its defer t.Stop() MUST live inside the
	// goroutine. Putting `defer t.Stop()` outside meant the deferred
	// Stop fired the instant RunModerationLoop returned (immediately
	// after launching the goroutine), killing the ticker before any
	// tick fired. The boot sweep ran once, then the for loop blocked
	// on a dead channel forever. Symptom: worker silent after first
	// boot sweep, no panics, no errors.
	go func() {
		t := time.NewTicker(tick)
		defer t.Stop()
		// One sweep at boot so a stream that's been live since restart
		// isn't ignored for the first interval.
		h.moderationSweep(ctx, providers, cfg, log)
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				h.moderationSweep(ctx, providers, cfg, log)
			}
		}
	}()
}

// moderationSweep is one tick of the adaptive moderation worker.
// Instead of scanning ALL live rooms every minute (which saturates
// VRAM-constrained local models at ~4 active broadcasts), we:
//   1. Ask the repo for the N rooms whose review is "due now",
//      ordered by oldest-due-first.
//   2. Process them sequentially (LM Studio = single-GPU = single
//      concurrent request anyway).
//   3. After each verdict update the room's next_due_at:
//        clean → grow interval (1m → 2m → 5m → 10m → 15m)
//        flag  → reset to 1m
//
// Result: a busy platform with 30 broadcasts where 25 are
// long-clean ends up checking ~5 rooms per minute (the suspicious
// + new ones), not 30. GPU pressure stays bounded.
//
// `maxPerTick` (from cfg) is the budget per sweep — the upper
// bound on rooms touched in one tick. Default 4 covers 4 single-
// GPU LM Studio inferences in 60 s.
func (h *Handler) moderationSweep(ctx context.Context, providers []moderation.Provider, cfg moderation.Config, log *slog.Logger) {
	limit := cfg.MaxPerTick
	if limit <= 0 {
		limit = 4
	}
	dueRooms, err := h.repo.ListReviewDue(ctx, limit)
	if err != nil {
		log.Warn("moderation: ListReviewDue failed", "err", err)
		return
	}
	for _, rd := range dueRooms {
		if rd.IsTest || rd.StreamKey == "" {
			continue
		}
		// We need the full Room for downstream logging (title) +
		// reports. ListReviewDue gives us the slim projection.
		full, ferr := h.repo.FindByID(ctx, rd.ID)
		if ferr != nil || full == nil || full.StreamKey == "" {
			continue
		}
		rm := full
		// Compose the thumbnail URL using the same convention the
		// admin patrol uses. The image is regenerated by server02's
		// sweeper every 30 s.
		thumbURL := strings.Replace(strings.TrimRight(h.hlsURL, "/"), "/hls", "/thumbs", 1) +
			"/" + full.StreamKey + ".jpg"

		// Per-room ctx with a generous timeout — LM Studio / Ollama
		// cold-loading a 30B+ model after TTL eviction can easily take
		// 60-90 s; cloud APIs (Claude/GPT/Gemini) come back in 1-3 s.
		// 120 s covers both cases. The worker is sequential so this
		// only stalls the rest of the sweep if every provider hangs;
		// happy path is well under a second per room.
		roomCtx, cancel := context.WithTimeout(ctx, 120*time.Second)
		v, errs := moderation.First(roomCtx, providers, thumbURL)
		cancel()
		if v == nil {
			if len(errs) > 0 {
				// slog renders []error as "[{}]"; stringify each.
				msgs := make([]string, len(errs))
				for i, e := range errs {
					msgs[i] = e.Error()
				}
				log.Warn("moderation: all providers failed",
					"roomId", rm.ID, "thumbURL", thumbURL, "errors", msgs)
			}
			continue
		}
		flagged := v.MaxScore >= cfg.Threshold

		// EVERY verdict (clean or flagged) gets an archived thumbnail
		// + a row in live_ai_verdicts. The 7-day sweep clears them;
		// admins can pin individual rows to keep them. This is the
		// audit trail that lets operators measure AI accuracy +
		// retrain on mismatches.
		evidenceURL := thumbURL
		if archived, err := archiveEvidence(thumbURL); err == nil {
			evidenceURL = archived
		} else {
			log.Warn("moderation: evidence archive failed",
				"roomId", rm.ID, "err", err)
		}

		// Build JSON for the scores column. Keys match the
		// moderation.Category enum so downstream readers don't
		// have to translate.
		scoresJSON := fmt.Sprintf(
			`{"nsfw":%.4f,"violence":%.4f,"politics":%.4f,"gambling":%.4f,"fraud":%.4f}`,
			v.Categories[moderation.CategoryNSFW],
			v.Categories[moderation.CategoryViolence],
			v.Categories[moderation.CategoryPolitics],
			v.Categories[moderation.CategoryGambling],
			v.Categories[moderation.CategoryFraud],
		)
		verdictID, vErr := h.repo.InsertVerdict(
			ctx, rm.ID, v.Provider, string(v.MaxCategory), v.MaxScore,
			scoresJSON, v.Reason, evidenceURL, flagged,
		)
		if vErr != nil {
			log.Warn("moderation: InsertVerdict failed",
				"roomId", rm.ID, "err", vErr)
		}

		// Bump this room's review schedule based on the verdict —
		// clean grows the interval, flagged resets it.
		_ = h.repo.UpdateReviewSchedule(ctx, rm.ID, flagged)

		if !flagged {
			log.Info("moderation: clean",
				"roomId", rm.ID, "verdictId", verdictID,
				"max", v.MaxScore, "cat", v.MaxCategory,
				"provider", v.Provider, "reason", v.Reason)
			continue
		}
		// Flagged → file a report row in the human-review queue
		// UNLESS an AI report for the same (room, category) is
		// already pending. Without this dedup, a room that's stuck
		// at NSFW=1.0 would generate a new report row every minute
		// and overwhelm the admin queue.
		hasPending, _ := h.repo.HasPendingAIReport(ctx, rm.ID, string(v.MaxCategory))
		if hasPending {
			log.Info("moderation: flagged (dedup, existing pending report)",
				"roomId", rm.ID, "verdictId", verdictID, "category", v.MaxCategory)
			continue
		}
		note := fmt.Sprintf("[AI:%s | 置信度 %.2f] %s",
			v.Provider, v.MaxScore, v.Reason)
		reportID, rErr := h.repo.InsertReportReturnID(
			ctx, rm.ID, nil, string(v.MaxCategory), note, evidenceURL,
		)
		if rErr != nil {
			log.Warn("moderation: InsertReport failed",
				"roomId", rm.ID, "err", rErr)
			continue
		}
		// Wire the verdict → report so admin UI can jump back and
		// forth + so "label as false_positive" can auto-dismiss
		// the linked report. reportID == 0 means the insert was a
		// duplicate (collapsed by the unique index) — no link.
		if verdictID > 0 && reportID > 0 {
			if err := h.repo.LinkVerdictReport(ctx, verdictID, reportID); err != nil {
				log.Warn("moderation: LinkVerdictReport failed", "err", err)
			}
		}
		log.Info("moderation: room flagged",
			"roomId", rm.ID, "title", rm.Title,
			"category", v.MaxCategory, "score", v.MaxScore,
			"provider", v.Provider, "verdictId", verdictID, "reportId", reportID)
	}
}

// RunVerdictCleanup periodically deletes verdicts older than maxAge
// that aren't pinned + unlinks the corresponding thumbnail files
// from /var/lib/dfchat/evidence. Pinned rows survive forever.
//
// Cadence: every 6 h. SweepOldVerdicts is a single DELETE…RETURNING
// so a few thousand-row sweeps stay under a second.
func (h *Handler) RunVerdictCleanup(ctx context.Context, maxAge time.Duration, log *slog.Logger) {
	go func() {
		t := time.NewTicker(6 * time.Hour)
		defer t.Stop()
		sweep := func() {
			thumbs, err := h.repo.SweepOldVerdicts(ctx, maxAge)
			if err != nil {
				log.Warn("verdict cleanup: SQL sweep failed", "err", err)
				return
			}
			if len(thumbs) == 0 {
				return
			}
			// Try to unlink each archived JPEG. The DB row is gone
			// either way; the file is just storage we'd otherwise
			// leak. EvidencePublicBase prefix tells us where the
			// served path maps to disk: strip the URL prefix and
			// prepend EvidenceDir.
			unlinked := 0
			for _, u := range thumbs {
				rel := strings.TrimPrefix(u, EvidencePublicBase)
				if rel == u || rel == "" {
					// Either not an archived URL (live thumb) or
					// already absolute; skip.
					continue
				}
				full := filepath.Join(EvidenceDir, rel)
				if err := os.Remove(full); err == nil {
					unlinked++
				}
			}
			log.Info("verdict cleanup: swept",
				"deleted_rows", len(thumbs), "unlinked_files", unlinked, "maxAge", maxAge)
		}
		// Run once at boot so old rows clear without waiting 6 h.
		sweep()
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				sweep()
			}
		}
	}()
}

// =================================================================
// Evidence archive helpers
// =================================================================
//
// AI moderation flips a room into the report queue right now, but
// the admin might not look at it for 5-30 minutes. By then the
// server02 thumbnail has been overwritten ~10 times — the
// "evidence" the admin clicks would show whatever was on screen at
// review time, not at flag time. That's useless for a regulator
// audit AND can flip an innocent-looking moment into a damning one
// (or vice versa).
//
// archiveEvidence pulls the thumbnail RIGHT NOW and copies it to a
// timestamped file path. Returns a URL the admin client can render
// from. Path is on local fs of server01 (where the api runs) so
// we don't need an extra MinIO upload step.

// EvidenceDir is where /api/v1/admin/live/evidence/<file> serves
// from. Configured via env so an operator can put it on a bigger
// disk if needed. Lives under /var/lib/dfchat by default.
var EvidenceDir = func() string {
	d := os.Getenv("MODERATION_EVIDENCE_DIR")
	if d == "" {
		d = "/var/lib/dfchat/evidence"
	}
	return d
}()

// EvidencePublicBase is the URL prefix where these files are served.
// Defaults to /api/v1/admin/live/evidence — gated by requireAdmin
// at the api layer. Override via MODERATION_EVIDENCE_BASE.
var EvidencePublicBase = func() string {
	b := os.Getenv("MODERATION_EVIDENCE_BASE")
	if b == "" {
		b = "/api/v1/admin/live/evidence"
	}
	return strings.TrimRight(b, "/")
}()

// archiveEvidence does:
//  1. GET imageURL → bytes
//  2. write to {EvidenceDir}/<yyyymmdd>/<stream_key>-<unix>.jpg
//  3. return the relative URL the admin client can hit
//
// Returns the URL on success. Caller should fall back to the live
// thumbnail URL on error — better to have stale evidence than no
// report.
func archiveEvidence(imageURL string) (string, error) {
	if err := os.MkdirAll(EvidenceDir, 0o755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", EvidenceDir, err)
	}
	hc := &http.Client{Timeout: 10 * time.Second}
	res, err := hc.Get(imageURL)
	if err != nil {
		return "", err
	}
	defer res.Body.Close()
	if res.StatusCode != 200 {
		return "", fmt.Errorf("fetch %s: status=%d", imageURL, res.StatusCode)
	}
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return "", err
	}
	// Build path: evidence/<yyyymmdd>/<base>-<unix>.jpg
	now := time.Now()
	day := now.Format("20060102")
	dir := filepath.Join(EvidenceDir, day)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	// Derive a deterministic-ish file name from the source URL +
	// nanosecond to defeat sub-second collisions.
	base := strings.TrimSuffix(filepath.Base(imageURL), ".jpg")
	name := fmt.Sprintf("%s-%d.jpg", base, now.UnixNano())
	full := filepath.Join(dir, name)
	if err := os.WriteFile(full, data, 0o644); err != nil {
		return "", err
	}
	return fmt.Sprintf("%s/%s/%s", EvidencePublicBase, day, name), nil
}
