package live

import (
	"context"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/dongfang/dfchat/server/internal/moderation"
)

// RunModerationLoop polls every IntervalSeconds for currently
// broadcasting rooms, asks the configured AI providers to look at
// each room's latest thumbnail, and files a system report
// (reporter_id = NULL) when any category exceeds the threshold.
//
// Same admin queue + UI as user reports — admin sees AI flags and
// human flags side by side, with AI's stated reason in the note
// field. Evidence images are captured AT FLAG TIME and copied to a
// permanent /opt/dfchat-live/data/evidence/<report_id>.jpg path so
// later review survives the 30 s thumbnail churn (this path doesn't
// exist yet — see evidence_archive.go for the helper).
//
// Stateless per-tick. If the api restarts mid-tick the worst case
// is one duplicate flag (the partial unique index catches dupes
// from the same provider for the same reason within a status=0
// window).
func (h *Handler) RunModerationLoop(ctx context.Context, cfg moderation.Config, log *slog.Logger) {
	if !cfg.Enabled {
		log.Info("moderation worker: disabled (MODERATION_ENABLED=false)")
		return
	}
	providers, err := moderation.Build(cfg)
	if err != nil {
		log.Warn("moderation worker: not starting", "err", err.Error())
		return
	}
	names := make([]string, 0, len(providers))
	for _, p := range providers {
		names = append(names, p.Name())
	}
	log.Info("moderation worker: started",
		"providers", names,
		"intervalSeconds", cfg.IntervalSeconds,
		"threshold", cfg.Threshold)

	tick := time.Duration(cfg.IntervalSeconds) * time.Second
	if tick < 10*time.Second {
		tick = 60 * time.Second
	}
	t := time.NewTicker(tick)
	defer t.Stop()
	go func() {
		// One sweep at boot so a stream that's been live since restart
		// isn't ignored for the first interval.
		h.moderationSweep(ctx, providers, cfg, log)
		for {
			select {
			case <-ctx.Done():
				return
			case <-t.C:
				h.moderationSweep(ctx, providers, cfg, log)
			}
		}
	}()
}

// moderationSweep is one tick: list live rooms, ask the providers,
// file reports for any flagged ones. We iterate sequentially per
// tick — a busy 10-room platform means at most 10 API calls per
// minute, well within rate limits and easy on cost.
func (h *Handler) moderationSweep(ctx context.Context, providers []moderation.Provider, cfg moderation.Config, log *slog.Logger) {
	rooms, err := h.repo.ListLive(ctx, ListLiveFilter{Limit: 100})
	if err != nil {
		log.Warn("moderation: ListLive failed", "err", err)
		return
	}
	for _, rm := range rooms {
		// Skip test-mode rooms (host-only preview) — they're not
		// public and don't need AI moderation.
		if rm.IsTest {
			continue
		}
		// ListLive returns rooms via the public SELECT that BLANKS
		// stream_key (anti-leak). Re-hydrate via FindByID to get
		// the real key for thumbnail URL construction. N+1 but the
		// patrol list rarely has more than a few dozen rooms.
		full, ferr := h.repo.FindByID(ctx, rm.ID)
		if ferr != nil || full == nil || full.StreamKey == "" {
			continue
		}
		// Compose the thumbnail URL using the same convention the
		// admin patrol uses. The image is regenerated by server02's
		// sweeper every 30 s.
		thumbURL := strings.Replace(strings.TrimRight(h.hlsURL, "/"), "/hls", "/thumbs", 1) +
			"/" + full.StreamKey + ".jpg"

		// Per-room ctx with a generous timeout — LM Studio / Ollama
		// cold-loading a 30B+ model after TTL eviction can easily take
		// 60-90 s; cloud APIs (Claude/GPT/Gemini) come back in 1-3 s.
		// 120 s covers both cases. The worker is sequential so this
		// only stalls the rest of the sweep if every provider hangs;
		// happy path is well under a second per room.
		roomCtx, cancel := context.WithTimeout(ctx, 120*time.Second)
		v, errs := moderation.First(roomCtx, providers, thumbURL)
		cancel()
		if v == nil {
			if len(errs) > 0 {
				// slog renders []error as "[{}]"; stringify each.
				msgs := make([]string, len(errs))
				for i, e := range errs {
					msgs[i] = e.Error()
				}
				log.Warn("moderation: all providers failed",
					"roomId", rm.ID, "thumbURL", thumbURL, "errors", msgs)
			}
			continue
		}
		if v.MaxScore < cfg.Threshold {
			// Logged at INFO so operators can see the worker is alive
			// and what each model is scoring. Useful for threshold
			// tuning + confirming Phase B is reaching the model.
			log.Info("moderation: clean",
				"roomId", rm.ID, "max", v.MaxScore, "cat", v.MaxCategory,
				"provider", v.Provider, "reason", v.Reason)
			continue
		}
		// Flagged! Build the report row. AI reports go in as
		// reporter_id = NULL; the unique-index ON CONFLICT skip
		// handles the case where the previous tick already flagged
		// the same room with the same category for the same provider.
		// We tag the provider into the note so the admin sees who
		// flagged it.
		note := fmt.Sprintf("[AI:%s | 置信度 %.2f] %s",
			v.Provider, v.MaxScore, v.Reason)

		// Archive the evidence frame so later review survives the
		// thumbnail churn. archiveErr is logged but not fatal — we
		// fall back to the live thumbnail URL.
		evidenceURL := thumbURL
		if archived, err := archiveEvidence(thumbURL); err == nil {
			evidenceURL = archived
		} else {
			log.Warn("moderation: evidence archive failed",
				"roomId", rm.ID, "err", err)
		}

		if err := h.repo.InsertReport(
			ctx, rm.ID, nil, string(v.MaxCategory), note, evidenceURL,
		); err != nil {
			log.Warn("moderation: InsertReport failed",
				"roomId", rm.ID, "err", err)
			continue
		}
		log.Info("moderation: room flagged",
			"roomId", rm.ID, "title", rm.Title,
			"category", v.MaxCategory, "score", v.MaxScore,
			"provider", v.Provider)
	}
}

// =================================================================
// Evidence archive helpers
// =================================================================
//
// AI moderation flips a room into the report queue right now, but
// the admin might not look at it for 5-30 minutes. By then the
// server02 thumbnail has been overwritten ~10 times — the
// "evidence" the admin clicks would show whatever was on screen at
// review time, not at flag time. That's useless for a regulator
// audit AND can flip an innocent-looking moment into a damning one
// (or vice versa).
//
// archiveEvidence pulls the thumbnail RIGHT NOW and copies it to a
// timestamped file path. Returns a URL the admin client can render
// from. Path is on local fs of server01 (where the api runs) so
// we don't need an extra MinIO upload step.

// EvidenceDir is where /api/v1/admin/live/evidence/<file> serves
// from. Configured via env so an operator can put it on a bigger
// disk if needed. Lives under /var/lib/dfchat by default.
var EvidenceDir = func() string {
	d := os.Getenv("MODERATION_EVIDENCE_DIR")
	if d == "" {
		d = "/var/lib/dfchat/evidence"
	}
	return d
}()

// EvidencePublicBase is the URL prefix where these files are served.
// Defaults to /api/v1/admin/live/evidence — gated by requireAdmin
// at the api layer. Override via MODERATION_EVIDENCE_BASE.
var EvidencePublicBase = func() string {
	b := os.Getenv("MODERATION_EVIDENCE_BASE")
	if b == "" {
		b = "/api/v1/admin/live/evidence"
	}
	return strings.TrimRight(b, "/")
}()

// archiveEvidence does:
//  1. GET imageURL → bytes
//  2. write to {EvidenceDir}/<yyyymmdd>/<stream_key>-<unix>.jpg
//  3. return the relative URL the admin client can hit
//
// Returns the URL on success. Caller should fall back to the live
// thumbnail URL on error — better to have stale evidence than no
// report.
func archiveEvidence(imageURL string) (string, error) {
	if err := os.MkdirAll(EvidenceDir, 0o755); err != nil {
		return "", fmt.Errorf("mkdir %s: %w", EvidenceDir, err)
	}
	hc := &http.Client{Timeout: 10 * time.Second}
	res, err := hc.Get(imageURL)
	if err != nil {
		return "", err
	}
	defer res.Body.Close()
	if res.StatusCode != 200 {
		return "", fmt.Errorf("fetch %s: status=%d", imageURL, res.StatusCode)
	}
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return "", err
	}
	// Build path: evidence/<yyyymmdd>/<base>-<unix>.jpg
	now := time.Now()
	day := now.Format("20060102")
	dir := filepath.Join(EvidenceDir, day)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	// Derive a deterministic-ish file name from the source URL +
	// nanosecond to defeat sub-second collisions.
	base := strings.TrimSuffix(filepath.Base(imageURL), ".jpg")
	name := fmt.Sprintf("%s-%d.jpg", base, now.UnixNano())
	full := filepath.Join(dir, name)
	if err := os.WriteFile(full, data, 0o644); err != nil {
		return "", err
	}
	return fmt.Sprintf("%s/%s/%s", EvidencePublicBase, day, name), nil
}
