#!/usr/bin/env bash
# DFCHAT — server02 deploy (run from dev box).
#
# Pushes deploy/server02/* + .env to /opt/dfchat-live and (re)starts the
# stack. Does NOT bootstrap — run bootstrap.sh on the box once first.
#
# Usage:
#   bash deploy/server02/deploy.sh

set -euo pipefail
trap 'echo "❌ server02 deploy failed at line $LINENO" >&2' ERR

PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$PROJECT_ROOT"

# Source dev-box secrets. Same .env.local that drives server01 deploy.
[ -f "$PROJECT_ROOT/.env.local" ] && set -a && . "$PROJECT_ROOT/.env.local" && set +a

HOST="${DFCHAT02_HOST:-45.119.4.109}"
PORT="${DFCHAT02_PORT:-13494}"      # post-bootstrap port
USER="${DFCHAT02_USER:-root}"
PASS="${DFCHAT02_PASSWORD:?Set DFCHAT02_PASSWORD in .env.local}"
REMOTE_DIR="${DFCHAT02_REMOTE_DIR:-/opt/dfchat-live}"

# Shared HMAC secret — MUST be the same value on server01 .env. Pulled
# from server01's deploy/.env.prod so we never drift.
SECRET_FROM_S01=$(grep -E '^LIVE_SRS_SECRET=' "$PROJECT_ROOT/deploy/.env.prod" | cut -d= -f2- || true)
if [ -z "$SECRET_FROM_S01" ]; then
  echo "❌ couldn't read LIVE_SRS_SECRET from deploy/.env.prod"
  echo "   server01 must have a value there first — it's the source of truth."
  exit 1
fi

SSH="sshpass -p $PASS ssh -p $PORT -o StrictHostKeyChecking=accept-new ${USER}@${HOST}"
RSH="sshpass -p $PASS ssh -p $PORT -o StrictHostKeyChecking=accept-new"

echo "==> 1/4  Building server02 .env (with shared LIVE_SRS_SECRET from server01)"
TMP_ENV=$(mktemp)
cat > "$TMP_ENV" <<EOF
# Auto-generated by deploy/server02/deploy.sh on $(date -u +%FT%TZ).
# Do not edit by hand — re-run the deploy script instead.
LIVE_SRS_SECRET=${SECRET_FROM_S01}
EOF
chmod 600 "$TMP_ENV"

echo "==> 2/4  Syncing configs to ${USER}@${HOST}:${REMOTE_DIR}/deploy"
$SSH "mkdir -p ${REMOTE_DIR}/deploy"
rsync -az --delete \
  -e "$RSH" \
  "$PROJECT_ROOT/deploy/server02/" "${USER}@${HOST}:${REMOTE_DIR}/deploy/"
sshpass -p "$PASS" scp -P "$PORT" -o StrictHostKeyChecking=accept-new \
  "$TMP_ENV" "${USER}@${HOST}:${REMOTE_DIR}/.env"
$SSH "chmod 600 ${REMOTE_DIR}/.env"
rm -f "$TMP_ENV"

echo "==> 3/4  Bootstrap self-signed cert if none present (chicken-and-egg)"
# nginx.conf has `listen 443 ssl` — without ANY cert file present nginx
# refuses to start, but certbot needs nginx serving /.well-known on :80
# first. Drop in a 1-day self-signed cert so the stack comes up. The
# real Let's Encrypt cert replaces it as soon as issue-cert.sh runs.
$SSH '
CERT_DIR=/opt/dfchat-live/data/letsencrypt/live/live.dfchat.chat
if [ ! -f "$CERT_DIR/fullchain.pem" ]; then
  mkdir -p "$CERT_DIR"
  apt-get install -y openssl >/dev/null 2>&1 || true
  openssl req -x509 -nodes -newkey rsa:2048 \
    -keyout "$CERT_DIR/privkey.pem" \
    -out    "$CERT_DIR/fullchain.pem" \
    -subj "/CN=live.dfchat.chat" \
    -days 1 2>/dev/null
  echo "  -> wrote 1-day self-signed bootstrap cert (replace via issue-cert.sh)"
else
  echo "  -> cert already present, skipping bootstrap"
fi'

echo "==> 4/4  docker compose up -d"
$SSH "cd ${REMOTE_DIR} && docker compose --env-file .env -f deploy/docker-compose.yml up -d --remove-orphans"

echo "==> 5/5  Quick health probe"
sleep 3
for i in 1 2 3 4 5; do
  if curl -sf --max-time 3 "http://${HOST}/healthz" >/dev/null 2>&1; then
    echo "  -> http://${HOST}/healthz OK (cert step still pending — uses :80)"
    break
  fi
  sleep 2
done

$SSH "cd ${REMOTE_DIR} && docker compose -f deploy/docker-compose.yml ps"

cat <<NEXT

✅ server02 stack up

Next manual steps (only the first time, after DNS resolves):
  1. ssh -p ${PORT} ${USER}@${HOST}
  2. bash /opt/dfchat-live/deploy/issue-cert.sh <your-email>
  3. Test from anywhere: curl -sI https://live.dfchat.chat/healthz
  4. Then run the server01 cutover (deploy/server02/server01_cutover.md).
NEXT
